CREATE TABLE dispatcher_processes (
    uuid VARBINARY(16) NOT NULL PRIMARY KEY,
    source_id INT(11) UNSIGNED NOT NULL,
    state VARCHAR(32) NOT NULL,
created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
