create table sources
(
    id                  int(11) unsigned auto_increment primary key,
    name                varchar(64)                                                         null,
    domain              varchar(64)                                                         null,
    status              enum ('hold', 'run', 'error', 'update') charset utf8 default 'hold' not null,
    stage               enum (
        'new',
        'quarantine',
        'prematch',
        'match',
        'live',
        'deprecated',
        'livenomatch',
        'passivematch'
        ) charset utf8                                                       default 'new'  not null,
    matching_group      tinyint                                              default 0      not null,
    matching_prio       tinyint                                              default 2      not null,
    matching_order      int unsigned                                         default 0      not null,
    update_photos       tinyint unsigned                                     default 1      not null,
    classified          tinyint                                              default 0      not null,
    created_at          datetime                                                            null,
    updated_at          datetime                                                            null,
    deleted_at          datetime                                                            null,
    crawler_type        varchar(64)                                                         null,
    crawler_type_images varchar(64)                                                         null,
    crawler_settings    text charset utf8                                                   null,
    settings            text charset utf8                                                   null,
    target_mode         varchar(2) charset utf8                              default 'v2'   not null,
    target_mode_version int(3) unsigned                                      default 4      not null,
    processing_flags    int unsigned                                         default 0      not null,
    post_actions        mediumtext charset utf8                                             null,
    country_code        varchar(2) charset utf8                                             null,
    specificity         int unsigned                                         default 0      not null
) collate = utf8_unicode_ci;
