INSERT INTO
    sources (
        id,
        name,
        domain,
        status,
        stage,
        matching_group,
        matching_prio,
        matching_order,
        update_photos,
        classified,
        created_at,
        updated_at,
        deleted_at,
        crawler_type,
        crawler_type_images,
        crawler_settings,
        settings,
        target_mode,
        target_mode_version,
        processing_flags,
        post_actions,
        country_code,
        specificity
    )
VALUES
    (
        1,
        'Engel & Völkers',
        'www.engelvoelkers.com',
        'run',
        'live',
        '0',
        2,
        94,
        1,
        1,
        '2015-05-14 06:51:18',
        '2015-05-14 06:51:18',
        null,
        'luminati_base',
        'luminati_unlimited',
        '{"crawler_page_threads":"1","crawler_page_rqps":"5","crawler_page_bucket_size":"50","crawler_multi":"yes","requests_client_mode":"cd","crawler_workflow":"normal","single_crawler_page_bucket_size":100,"alert_min_volume_percent":"0.15","alert_outliers_magnitude":"1.5","use_cs_for_duplicates_search":0,"infinite_pager_detector_off":"0","match_url_by_content_comparator_on":"0","reload_page_before_images":0,"incremental_force_update_on":"0","incremental_force_update_days":"7","incremental_force_update_max_objects":"100","fix_ip":"0","crawler_search":"luminati_base","crawler_search_type":"basic","fast_processing_source_id":"","get_links_mt":"parallel_price_ranges","disable_autofix_mask":0,"trust_coordinates_from_se":1,"crawler_sleep_between_buckets":"60","dynamic_proxy_name_for_images":"oxylabs_100_romania","dynamic_proxy_name_for_pages":"luminati_base","dynamic_proxy_name_for_post_sources":"","dynamic_proxy_name_for_search":"luminati_base","get_links_timeout_from":1,"get_links_timeout_step":0,"get_links_timeout_to":1,"load_links_timeout_from":"","load_links_timeout_step":"","load_links_timeout_to":"","photos_batch_rqps":null,"photos_batch_threads_count":null,"skip_links_outlier":0,"skip_new_in_sections":"","useMigration":false,"crawler_post_source":"luminati_base"}',
        '{"processing_pool":"basic","pause":0,"pause_by_patch":0,"daily_delayed_till":"","custom_url_var_field_key":"","join_ses_by":"7","max_processing_days":"1","processing_days_interval":"1","location_ids_for_matching":[],"minimal_price_for_matching":"100000","minimal_rent_price_for_matching":"1000"}',
        'v2',
        4,
        138,
        '',
        'ES',
        4096
    );

INSERT INTO
    sources (
        id,
        name,
        domain,
        status,
        stage,
        matching_group,
        matching_prio,
        matching_order,
        update_photos,
        classified,
        created_at,
        updated_at,
        deleted_at,
        crawler_type,
        crawler_type_images,
        crawler_settings,
        settings,
        target_mode,
        target_mode_version,
        processing_flags,
        post_actions,
        country_code,
        specificity
    )
VALUES
    (
        2506,
        'Idealista',
        'www.idealista.pt',
        'run',
        'match',
        '0',
        2,
        0,
        126,
        1,
        '2015-05-14 06:51:18',
        '2015-05-14 06:51:18',
        null,
        'dynamic',
        'dynamic',
        '{"crawler_page_threads":"-1","crawler_page_rqps":"100","crawler_page_bucket_size":"200","crawler_multi":"yes","requests_client_mode":"cd","crawler_workflow":"blocks_data","single_crawler_page_bucket_size":100,"alert_min_volume_percent":"0.15","alert_outliers_magnitude":"1.5","use_cs_for_duplicates_search":0,"infinite_pager_detector_off":"0","match_url_by_content_comparator_on":"0","reload_page_before_images":0,"incremental_force_update_on":"0","incremental_force_update_days":"7","incremental_force_update_max_objects":"750","fix_ip":"0","crawler_search":"dynamic","crawler_search_type":"","fast_processing_source_id":"7032","get_links_mt":"parallel_price_ranges","disable_autofix_mask":0,"trust_coordinates_from_se":1,"useMigration":false,"crawler_sleep_between_buckets":"4","dynamic_proxy_name_for_images":"oxylabs_100_romania","dynamic_proxy_name_for_pages":"zenrows_for_idealista","dynamic_proxy_name_for_post_sources":"","dynamic_proxy_name_for_search":"zenrows_for_idealista","get_links_timeout_from":"","get_links_timeout_step":"","get_links_timeout_to":"","load_links_timeout_from":"","load_links_timeout_step":"","load_links_timeout_to":"","photos_batch_rqps":null,"photos_batch_threads_count":null,"skip_links_outlier":0,"skip_new_in_sections":"","crawler_post_source":"luminati_base"}',
        '{"processing_pool":"basic","pause":0,"pause_by_patch":0,"daily_delayed_till":"","custom_url_var_field_key":"","join_ses_by":"7","max_processing_days":"1","processing_days_interval":"1"}',
        'v2',
        4,
        136,
        '',
        'PT',
        0
    );
