use mvp;
INSERT INTO sources (id,
                     name,
                     status,
                     stage,
                     matching_group,
                     matching_prio,
                     matching_order,
                     update_photos,
                     classified,
                     created_at,
                     updated_at,
                     deleted_at,
                     settings,
                     target_mode,
                     target_mode_version,
                     processing_flags,
                     post_actions,
                     country_code,
                     specificity)
VALUES (1,
        'Source 1',
        'run',
        'live',
        '0',
        2,
        94,
        1,
        1,
        '2015-05-14 06:51:18',
        '2015-05-14 06:51:18',
        null,
        '{"processing_pool":"basic","pause":0,"pause_by_patch":0,"daily_delayed_till":"","max_processing_days":"1","processing_days_interval":"1"}',
        'v2',
        4,
        138,
        '',
        'ES',
        4096);

INSERT INTO sources (id,
                     name,
                     status,
                     stage,
                     matching_group,
                     matching_prio,
                     matching_order,
                     update_photos,
                     classified,
                     created_at,
                     updated_at,
                     deleted_at,
                     settings,
                     target_mode,
                     target_mode_version,
                     processing_flags,
                     post_actions,
                     country_code,
                     specificity)
VALUES (2,
        'Source 2',
        'run',
        'match',
        '0',
        2,
        0,
        126,
        1,
        '2015-05-14 06:51:18',
        '2015-05-14 06:51:18',
        null,
        '{"processing_pool":"basic","pause":0,"pause_by_patch":0,"daily_delayed_till":"","join_ses_by":"7","max_processing_days":"1","processing_days_interval":"1"}',
        'v2',
        4,
        136,
        '',
        'PT',
        0);
